const ProductImg =[
	{
	id:1,
	image:`${process.env.PUBLIC_URL}/images/pizza-01.png`,
	name:'Spicy BBQ Chicken Pizza',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:7.98,
	},
	{
	id:2,
	image:`${process.env.PUBLIC_URL}/images/pizza-02.png`,
	name:'Prosciutto & Arugula Pizza',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:7.98,
	},
	{
	id:3,
	image:`${process.env.PUBLIC_URL}/images/pizza-03.png`,
	name:'Buffalo Chicken Pizza',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:7.98
	},
	{
	id:4,
	image:`${process.env.PUBLIC_URL}/images/pasta-04.png`,
	name:'Pancetta Spaghetti',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:7.98,
	},
	{
	id:5,
	image:`${process.env.PUBLIC_URL}/images/pasta-05.png`,
	name:'Fettuccine Alfredo',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:7.98,
	},
	{
	id:6,
	image:`${process.env.PUBLIC_URL}/images/pasta-06.png`,
	name:'Tuna pasta bake',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:7.98
	},
	{
	id:7,
	image:`${process.env.PUBLIC_URL}/images/pasta-07.png`,
	name:'Spaghetti Bolognese',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:7.98,
	},
	{
	id:8,
	image:`${process.env.PUBLIC_URL}/images/dessert-08.png`,
	name:'Chocolate Cake',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:7.98,
	},
	{
	id:9,
	image:`${process.env.PUBLIC_URL}/images/dessert-09.png`,
	name:'Cheesecake',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:7.50,
	},
	{
	id:10,
	image:`${process.env.PUBLIC_URL}/images/dessert-10.png`,
	name:'Belgian Waffle',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:7.98,
	},
	{
	id:11,
	image:`${process.env.PUBLIC_URL}/images/dessert-11.png`,
	name:'Strawberry Caken',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:7.98,
	},
	{
	id:12,
	image:`${process.env.PUBLIC_URL}/images/salad-12.png`,
	name:'Turkey Salad',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:5.50,
	},
	{
	id:13,
	image:`${process.env.PUBLIC_URL}/images/salad-13.png`,
	name:'Spinach Salad',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:5.50,
	},
	{
	id:14,
	image:`${process.env.PUBLIC_URL}/images/burger-14.jpg`,
	name:'Crispy Chicken',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:8.50,
	},
	{
	id:15,
	image:`${process.env.PUBLIC_URL}/images/burger-15.jpg`,
	name:'Ultimate Bacon',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:9.99,
	},
	{
	id:16,
	image:`${process.env.PUBLIC_URL}/images/burger-16.jpg`,
	name:'Black Sheep',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:9.99,
	},
	{
	id:17,
	image:`${process.env.PUBLIC_URL}/images/burger-17.jpg`,
	name:'Double Burger',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:10.35,
	},
	{
	id:18,
	image:`${process.env.PUBLIC_URL}/images/burger-18.jpg`,
	name:'Turkey Burger',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:10.35,
	},
	{
	id:19,
	image:`${process.env.PUBLIC_URL}/images/burger-19.jpg`,
	name:'Smokey House',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:9.50,
	},
	{
	id:20,
	image:'images/burger-20.jpg',
	name:'Panish Burger',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:9.50,
	},
	{
	id:21,
	image:`${process.env.PUBLIC_URL}/images/burger-21.jpg`,
	name:'Bigti Burger',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:10.50,
	},
	{
	id:22,
	image:`${process.env.PUBLIC_URL}/images/burger-22.png`,
	name:'Classic Burger',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:10.50,
	},
	{
	id:23,
	image:`${process.env.PUBLIC_URL}/images/burger-23.png`,
	name:'Sough Burger',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:10.50,
	},
	{
	id:24,
	image:`${process.env.PUBLIC_URL}/images/side-23.png`,
	name:'French Fries',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:10.50,
	},
	{
	id:25,
	image:`${process.env.PUBLIC_URL}/images/side-24.png`,
	name:'Mozzarella Sticks',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:10.50,
	},
	{
	id:26,
	image:`${process.env.PUBLIC_URL}/images/side-26.png`,
	name:'Onion Rings',
	content:'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula rutrum risus…',
	price:10.50,
	},
];
export default ProductImg