const InstaImage =[
	{
	id:1,
	image:`${process.env.PUBLIC_URL}/images/instagram1.jpg`,
	},
	{
	id:2,
	image:`${process.env.PUBLIC_URL}/images/instagram2.jpg`,
	},
	{
	id:3,
	image:`${process.env.PUBLIC_URL}/images/instagram3.jpg`,
	},
	{
	id:4,
	image:`${process.env.PUBLIC_URL}/images/instagram4.jpg`,
	},
	{
	id:5,
	image:`${process.env.PUBLIC_URL}/images/instagram5.jpg`,
	},
	{
	id:6,
	image:`${process.env.PUBLIC_URL}/images/instagram6.jpg`,
	},
	{
	id:7,
	image:`${process.env.PUBLIC_URL}/images/instagram7.jpg`,
	},
	{
	id:8,
	image:`${process.env.PUBLIC_URL}/images/instagram8.jpg`,
	},
	{
	id:9,
	image:`${process.env.PUBLIC_URL}/images/instagram9.jpg`,
	},
	{
	id:10,
	image:`${process.env.PUBLIC_URL}/images/instagram10.jpg`,
	},
	{
	id:11,
	image:`${process.env.PUBLIC_URL}/images/instagram1.jpg`,
	},
	{
	id:12,
	image:`${process.env.PUBLIC_URL}/images/instagram2.jpg`,
	},
];
export default InstaImage